name: MegaJump
main: me.flungo.bukkit.MegaJump.MagaJump
version: 0.1.0
description: >
              Makes you jump.... really high!
commands:
    mj:
        description: Toggle megajump
        usage: /mj [amplifier]