name: MegaJump
main: me.flungo.bukkit.MegaJump.MegaJump
version: 0.2.0
description: >
              Makes you jump.... really high!
commands:
    mj:
        description: Toggle megajump
        usage: |
              /mj - Tooggle MegaJump
              /mj <user>
              /mj <amplifier>
              /mj <user> <amplifier>